# Set prefix key
set-option -g prefix C-f
set-option -g prefix2 C-j

# Quickly reload tmux configurattion
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf
reloaded."

# Mouse mode
set -g mouse on
set -g default-terminal "tmux-256color"

# Vi-style pane navigation (no prefix binding)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# Quickly split panes
bind | split-window -h
bind - split-window -v

# Move status bar to the top
set -g status-position top

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

# load the catppuccin plugin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line more pleasant.
set -g status-left ""
# set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# FORCE the background color to match your terminal/flavor after loading
# (Change #1e1e2e to your specific terminal background color if not using Mocha)
set -g status-bg "#1e1e2e"

# Ensure that everything on the right side of the status line is included.
set -g status-right-length 100

set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

