# Set prefix key
set-option -g prefix C-f
set-option -g prefix2 C-j

# Quickly reload tmux configurattion
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf
reloaded."

# Mouse mode
set -g mouse on

# Vi-style pane navigation (no prefix binding)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# Quickly split panes
bind | split-window -h
bind - split-window -v

# Move status bar to the top
set -g status-position top

# add the catppuccin color scheme
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
